# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily Report

on:
  schedule:
    - cron: '5 16,17,18 * * *'
  workflow_dispatch:

jobs:
  Report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Required
      run: |
        pip install -r requirements.txt
    
    - name: Report
      env:
          userinfo: ${{ secrets.USERINFO }}
          location:  ${{ secrets.LOCATION }}
          other: ${{ secrets.OTHER }}
      run: |
        python main.py
